version: "3"
services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: <YourStrong!Passw0rd>
      MSSQL_PID: Developer
    ports:
      - 1433:1433
  tools:
    image: mcr.microsoft.com/mssql-tools
    command: [
      "/bin/bash",
      "-c",
      "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S database -U sa -P '<YourStrong!Passw0rd>' -Q \"IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'arrangement-db') BEGIN CREATE DATABASE [arrangement-db]; END\""
    ]
    depends_on:
      - database
