version: "3"
services:
  database:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: <YourStrong!Passw0rd>
      MSSQL_PID: Developer
    ports:
      - 1433:1433
  tools:
    image: mcr.microsoft.com/mssql-tools
    command:
      - /bin/bash
      - -c
      - |
        sleep 30
        /opt/mssql-tools/bin/sqlcmd \
          -S database \
          -U sa \
          -P $$DB_PASSWORD \
          -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '$$DB_NAME') BEGIN CREATE DATABASE [$$DB_NAME]; END"
    environment:
      DB_NAME: arrangement-db
      DB_PASSWORD: <YourStrong!Passw0rd>
    depends_on:
      - database
