name: Bekk reusable Arrangement-svc workflow

on:
  workflow_call: 
    # Legg til descriptions
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      IMAGE:
        required: false
        type: string
      IMAGE_TAG:
        required: false
        type: string
      TERRAFORM_WORKSPACE:
        required: false
        type: string
      TERRAFORM_VAR_FILE:
        required: false
        type: string
        default: "dev.tfvars"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      CONNECTIONSTRINGS__EVENTDB:
        required: true
      SENDGRID__APIKEY:
        required: true

jobs:
  build:
    name: build and terraform
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile deploy
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile deploy

      - name: Terraform Format
        working-directory: terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        id: validate
        run: terraform validate -no-color

      - name: Create and change Terraform workspace
        working-directory: terraform
        id: workspace
        run: |
          terraform workspace select ${{ inputs.TERRAFORM_WORKSPACE }} \
          || terraform workspace new ${{ inputs.TERRAFORM_WORKSPACE }}

      - name: Terraform apply review app
        working-directory: terraform
        id: apply-review
        if: github.event_name == 'pull_request'
        run: |
          terraform apply -auto-approve -var-file "${{ inputs.TERRAFORM_VAR_FILE }}" -no-color \
            -var "sendgrid_apikey=${{ secrets.SENDGRID__APIKEY }}" \
            -var "connectionstring_eventdb=${{ secrets.CONNECTIONSTRINGS__EVENTDB }}" \
            -var "preview_name=${{ inputs.TERRAFORM_WORKSPACE }}" \
            -var "create_dns_record=true" \
            -var "task_image=${{ inputs.IMAGE }}" \
            -var "task_image_tag=${{ inputs.IMAGE_TAG }}"
          echo "::set-output name=preview_url::$(terraform output URL)"

      - name: Create and change Terraform workspace for dev
        working-directory: terraform
        id: workspace-dev
        run: |
          terraform workspace select dev \
          || terraform workspace new dev

      - name: Terraform plan for merge
        working-directory: terraform
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -var-file "${{ inputs.TERRAFORM_VAR_FILE }}" -no-color \
            -var "sendgrid_apikey=${{ secrets.SENDGRID__APIKEY }}" \
            -var "connectionstring_eventdb=${{ secrets.CONNECTIONSTRINGS__EVENTDB }}" \
            -var "task_image=${{ inputs.IMAGE }}" \
            -var "task_image_tag=latest"
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            
            <details><summary>Show plan for apply after merge to master</summary>
            
            \`\`\`\n
            ${ process.env.PLAN }
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1