name: Build and deploy arrangement-svc to prod

on:
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore

  build:
    name: Build and push docker image
    uses: bekk/bekk-ci-workflows/.github/workflows/build.yml@master
    with:
      IMAGE_TAG: ${{ github.event.release.tag_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.BEKK_BASEN_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.BEKK_BASEN_SECRET_ACCESS_KEY_PROD }}

  deploy:
    name: Deploy arrangement-svc to prod
    uses: bekk/bekk-ci-workflows/.github/workflows/deploy.yml@master
    needs: build
    with:
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      TERRAFORM_WORKSPACE: prod
      TERRAFORM_VAR_FILE: prod.tfvars
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.BEKK_BASEN_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.BEKK_BASEN_SECRET_ACCESS_KEY_PROD }}
      SSH_PRIVATE_KEY: ${{ secrets.BEKK_BASEN_TERRAFORM_SSH_PRIVATE_KEY }}
