name: Build and deplo PR review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master

jobs:
  build:
    name: Build and push docker image
    uses: ./.github/workflows/build.yml
    if: ${{ github.event.action != 'closed' }}
    with:
      ENVIRONMENT: development
      ECR_REPOSITORY: "bekk-arrangement-svc"
      IMAGE_TAG: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    name: Deploy arrangement-svc for review
    uses: ./.github/workflows/review.yml
    needs: build
    with:
      ENVIRONMENT: development
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      TERRAFORM_WORKSPACE: $GITHUB_HEAD_REF
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}