name: Build and deploy arrangement-svc

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - master

jobs:
  build:
    name: Build and push docker image
    uses: ./.github/workflows/build.yml
    if: github.event.pull_request.closed == false
    with:
      ENVIRONMENT: development
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    name: Deploy arrangement-svc for review
    uses: ./.github/workflows/review.yml
    needs: build
    with:
      ENVIRONMENT: development
      IMAGE: ${{ needs.build.outputs.image }}
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      TERRAFORM_WORKSPACE: $GITHUB_HEAD_REF
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      CONNECTIONSTRINGS__EVENTDB: ${{ secrets.CONNECTIONSTRINGS__EVENTDB }}
      SENDGRID__APIKEY: ${{ secrets.SENDGRID__APIKEY }}