name: Build and deploy PR for review

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: ARRANGEMENT_SVC_CONTAINER_MANAGER=docker dotnet test --no-restore
        env:
            OFFICEEVENTS__TENANTID: ${{ secrets.OFFICEEVENTS__TENANTID }}
            OFFICEEVENTS__MAILBOX: ${{ secrets.OFFICEEVENTS__MAILBOX }}
            OFFICEEVENTS__CLIENTID: ${{ secrets.OFFICEEVENTS__CLIENTID }}
            OFFICEEVENTS__CLIENTSECRET: ${{ secrets.OFFICEEVENTS__CLIENTSECRET }}


  build:
    if: contains(github.event.pull_request.title, 'preview')
    name: Build and push docker image
    uses: bekk/bekk-ci-workflows/.github/workflows/build.yml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.BEKK_BASEN_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.BEKK_BASEN_SECRET_ACCESS_KEY_DEV }}

  deploy:
    if: contains(github.event.pull_request.title, 'preview')
    name: Deploy arrangement-svc for review
    uses: bekk/bekk-ci-workflows/.github/workflows/review.yml@master
    needs: build
    with:
      IMAGE_NAME: ${{ needs.build.outputs.image_name }}
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      TERRAFORM_WORKSPACE: $GITHUB_HEAD_REF
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.BEKK_BASEN_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.BEKK_BASEN_SECRET_ACCESS_KEY_DEV }}
      SSH_PRIVATE_KEY: ${{ secrets.BEKK_BASEN_TERRAFORM_SSH_PRIVATE_KEY }}
